# Generated by Django 5.0.6 on 2024-06-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_activity', to='TrainingAPIApp.activity'),
            preserve_default=False,
        ),
    ]
