# Generated by Django 5.0.6 on 2024-05-30 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingAPIApp', '0003_bulletin_statute_alter_user_user_role_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
