# Generated by Django 5.0.6 on 2024-05-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingAPIApp', '0004_bulletin_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_code',
        ),
    ]
