# Generated by Django 5.0.6 on 2024-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingAPIApp', '0005_remove_department_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_finished',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
