# Generated by Django 5.0.6 on 2024-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingAPIApp', '0007_remove_student_full_name_student_student_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='department',
            name='active',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='active',
        ),
        migrations.RemoveField(
            model_name='like',
            name='active',
        ),
        migrations.RemoveField(
            model_name='missingactivityreport',
            name='active',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='active',
        ),
        migrations.RemoveField(
            model_name='statute',
            name='active',
        ),
        migrations.RemoveField(
            model_name='studentactivity',
            name='active',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='klass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='missingactivityreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
